Preserve data
ciraganenicole/School-library pull request #6
Opened 2022-06-22 09:11 UTC by moise-mulungu

On this milestone, We:
- Saved data for `@books,` `@people` and `@rentals`.
- Created a new file named `data.rb` for data methods.
- Added loaded methods inside the data file.
- Created a `saved.rb` file to save all the data.
- Updated the README file.

2022-06-22 09:34 UTC, Omar-Muhamad requested changes
# Changes Required ♻️
### Hi @moise-mulungu and @ciraganenicole,

Nice job, you are almost there.

![](https://camo.githubusercontent.com/56bcd754643682fcc078b66eaa7278dead6c9c5013595c875b4ddcbe0f0ef0aa/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f78554f786668365a4d373565664d3342716f2f67697068792d646f776e73697a65642d6d656469756d2e676966)

## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- Github flow is used correctly. ✔
- All linters checks are ok. ✔

## (Changes Required) Aspects to improve: ♻️

- [ ] Please check the inline comments below.

## [Optional] suggestions:

- Nothing to mention.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-06-22 09:34 UTC, omar-muhamad commented on data.rb
> +end
- [ ] When the user adds books or people and exits the app this data suppose to be saved in the `.json` meant for that but this is not happening, So please fix that.

2022-06-22 09:34 UTC, omar-muhamad commented on app.rb
>      @rentals = []
- [ ] Please add `rentals_loaded` that you created in `data.rb` here instead of an empty array to load rentals saved when the app loaded.

2022-06-23 11:04 UTC, uwadonat approved these changes
Hi **@Team,**

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
# Hightlights
- No linter errors ✔️
- Clean and well organized code ✔️
![appr3](https://user-images.githubusercontent.com/65860678/175284164-a14085c3-0b6c-4e16-99dd-080529595b03.gif)

# Status: Approved ✔️✔️✔️

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-06-23 11:07 UTC, merged